### ISSUE TITLE
Global context doesn't work with Blade layouts

### ISSUE THREAD

**Issue by galengidman** [htmlburger/wpemerge#12]
## Version

  - WP Emerge: 0.11.1
  - WordPress: 5.2.1
  - PHP: 7.2.0

## Expected behavior

Adding a view global should create a key/value pair in the `$global` array.

## Actual behavior

It does not.

## Steps to reproduce (in case of a bug)

1. Completely blank WP theme. Empty `style.css`, `functions.php`, `index.php`.
2. Install WPEmerge and WPEmerge Blade via Composer.
3. Add following to `functions.php`:
```php
require_once( 'vendor/autoload.php' );

add_action( 'after_setup_theme', function() {
    WPEmerge::boot( [
        'providers' => [
            \WPEmergeBlade\View\ServiceProvider::class,
        ],
        'blade' => [
            'options' => [
                'views' => get_template_directory() . '/views',
            ],
        ],
    ] );

    View::addGlobal( 'foo', 'bar' );

    Router::get( '/', function() {
        return app_view( 'index' );
    } );
} );
```
4. Create new `views/index.blade.php` with the following:
```php
{{ dd($global) }}
```
5. Outputs empty array.

## Comments

Seems to work fine using the default PHP view engine, but not with Blade. [Here's a zip file](http://galen.in/4a03yG) of the theme test case.

**Comment by atanas-angelov-dev** [comment]
Hi @galengidman ,

This is due to an unfortunate race condition - the view engine gets initialized with the globals before they are registered.
This is not the case with the default view engine as it always reads the globals immediately before creating the view instance.

To work around this you will need to create a small service provider class like this:
```php
use WPEmerge\ServiceProviders\ServiceProviderInterface;

class ViewGlobalsServiceProvider implements ServiceProviderInterface {
    public function register( $container ) {
        // Nothing to register.
    }

    public function boot( $container ) {
        View::addGlobal( 'foo', 'bar' );
    }
}
```

... and then register it before the Blade service provider:
```php
'providers' => [
    ViewGlobalsServiceProvider::class,
    \WPEmergeBlade\View\ServiceProvider::class,
],
```

This should be fixed in the next release - thanks for the report!

**Comment by atanas-angelov-dev** [comment]
Fixed in `master`.

**Comment by galengidman** [comment]
Thanks for the quick answer and fix @atanas-angelov-dev!
