### ISSUE TITLE
error while installing and some questions 

### ISSUE THREAD

**Issue by thunderjet12** [htmlburger/wpemerge#20]
thanks the awesome framework and I have some questions :

{ NOTE: I installed the starter theme but it took me much time especially I got an error when setting it up in bedrock + homestead  thee error happen most times is "wpemerge\cli\app::createconfigjson"  this was in my manjaro setup 
 I tried at my windows setup and things went well until  TTY mode not supported appeared so I used ./vendor/bin/wpemerge install and said yes for most option including installing carbon fields 
and here I got error composer not recognized as an internal command  ...   so I used the command 
composer require htmlburger/wpemerge from "framework docs - quickstart" inside the newly created theme Dir and the command worked then I used again  ./vendor/bin/wpemerge install and said yes to most options Except installing carbon fields and activated the theme with 1 error  (constant REQUEST_URI - assumed 'REQUEST_URI' (this will throw an Error in a future version of PHP) in F:\xamppm\htdocs\wordpress_test\wp-content\themes\gamemag\theme\functions.php on line 74)  with some HTML markup at the site home page  }. 
images
![Screenshot (2)](https://user-images.githubusercontent.com/9190729/74583850-638bf880-4fd4-11ea-8888-852e21b90ee2.png)
![Screenshot (3)](https://user-images.githubusercontent.com/9190729/74583856-70a8e780-4fd4-11ea-8f6e-d962f74b65f0.png)

SO: did I do something wrong?

Questions: -

#1  Can I use the starter theme for my new premium theme I want to sell it in many different market places ThemeForest is one of them?

#2 I want to create a full admin plugin to support it and any new themes I want to create, so the question is does the framework have good support for plugins and if there are limitations?

#3 speaking of Themeforest your starter theme has many things that seem relies on composer SUCH AS AUTOLOAD  so does that how will buy my theme should have composer installed in his live host.  "### because I thought I can zip the final build and upload it for review and then for customers"?

#4 I read in Envato forums that most Envato customers are developers that use those premium items to build websites for customers and that many of them aren't have that high skills so I'm frustrated that I'm using modern tools for that I spent week now searching for a good framework that 
not so advance and powerful at the same time and I checked Beans, cherry,  unyson and modern MVC:  themosis, lumberjack, timber,typerocket and then found yours and seems fit most of my needs so what your thoughts or tips?

best regards ^_^

**Comment by atanas-dev** [comment]
Hi @thunderjet12 ,

> REQUEST_URI - assumed 'REQUEST_URI'

This looks like an issue in your theme's functions.php. From what I can see you are most probably using `$_SERVER[REQUEST_URI]` which should be `$_SERVER['REQUEST_URI']` instead at line 74.

> Can I use the starter theme for my new premium theme I want to sell it in many different market places ThemeForest is one of them?

Both the starter theme and framework are distributed as GPLv2 so from a licensing stand-point you are free to do so, but I cannot guarantee that ThemeForest will accept it (the current release uses an unusual directory structure).

> does the framework have good support for plugins and if there are limitations?

The currently published version of the framework does not have support for usage in plugins but the next release will. Unfortunately there is still a lot to be done before the next release is ready.

> does that how will buy my theme should have composer installed in his live host

No, the end user won't need to have composer installed. The `yarn release` script will install all production-only dependencies so the end user won't have to deal with composer. Note that the produced zip at this point is NOT uploadable via the /wp-admin/ interface (only manually via SFTP upload or other custom deployment process).
This limitation will also be fixed in the next release.

> what your thoughts or tips?

Make sure you read through the docs (https://docs.wpemerge.com/#/) as there are a number of utilities and shortcuts that you may miss otherwise. Also give the blog a read (https://wpemerge.com/blog/) as there are a couple articles that will explain some features in more detail (e.g. https://wpemerge.com/2019/01/24/view-composers-passing-data-and-staying-dry/)

**Comment by thunderjet12** [comment]
Thanks for the fast response and your answers solved many of my concerns
and looking forward to your next release and I will do as you said.

regards ^_^

**Comment by thunderjet12** [comment]
> Hi @thunderjet12 ,
> 
> > REQUEST_URI - assumed 'REQUEST_URI'
> 
> This looks like an issue in your theme's functions.php. From what I can see you are most probably using `$_SERVER[REQUEST_URI]` which should be `$_SERVER['REQUEST_URI']` instead at line 74.
> 
> > Can I use the starter theme for my new premium theme I want to sell it in many different market places ThemeForest is one of them?
> 
> Both the starter theme and framework are distributed as GPLv2 so from a licensing stand-point you are free to do so, but I cannot guarantee that ThemeForest will accept it (the current release uses an unusual directory structure).
> 
> > does the framework have good support for plugins and if there are limitations?
> 
> The currently published version of the framework does not have support for usage in plugins but the next release will. Unfortunately there is still a lot to be done before the next release is ready.
> 
> > does that how will buy my theme should have composer installed in his live host
> 
> No, the end user won't need to have composer installed. The `yarn release` script will install all production-only dependencies so the end user won't have to deal with composer. Note that the produced zip at this point is NOT uploadable via the /wp-admin/ interface (only manually via SFTP upload or other custom deployment process).
> This limitation will also be fixed in the next release.
> 
> > what your thoughts or tips?
> 
> Make sure you read through the docs (https://docs.wpemerge.com/#/) as there are a number of utilities and shortcuts that you may miss otherwise. Also give the blog a read (https://wpemerge.com/blog/) as there are a couple articles that will explain some features in more detail (e.g. https://wpemerge.com/2019/01/24/view-composers-passing-data-and-staying-dry/)


Thanks for the fast response and your answers solved many of my concerns
and looking forward to your next release and I will do as you said.

regards ^_^
